---
# tasks for install role
- name: Add GitLab repository
  ansible.builtin.shell:
    cmd: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash

- name: Install GitLab Runner
  ansible.builtin.apt:
    name: gitlab-runner
    update_cache: yes

# - name: Copy Docker and app files
#   ansible.builtin.copy:
#     src: files/app
#     dest: /

# - name: Create volume and change permissions
#   ansible.builtin.file:
#     path: /app
#     mode: '0775'
#     state: directory

